version: '3.8'

services:
  user-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user_catalog_db
    ports:
      - "5434:5432"

  tracking-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tracking_db
    ports:
      - "5433:5432"